jobs:
  checkov:
    machine: true
    steps:
      - checkout

      - run:
          command: docker run --rm -w /src -v $(pwd):/src bridgecrew/checkov -d aws -o json | tee checkov-output.json || true

      - store_artifacts:
          path: checkov-output.json
          destination: checkov-artifact
          when: always

workflows:
  version: 2
  terraform:
    jobs:
      - checkov
