jobs:
  tfsec:
    machine: true
    steps:
      - checkout

      - run:
          command: docker run --rm -v $(pwd):/src aquasec/tfsec /src -f json | tee tfsec-output.json || true

      - store_artifacts:
          path: tfsec-output.json
          destination: tfsec-artifacts
          when: always

workflows:
  version: 2
  terraform:
    jobs:
      - tfsec
