jobs:
  terrascan:
    machine: true
    steps:
      - checkout

      - run:
          command: docker run --rm -v $(pwd):/src tenable/terrascan scan -t aws -d /src/aws -o json | tee terrascan-output.json || true

      - store_artifacts:
          path: terrascan-output.json
          destination: terrascan-artifacts
          when: always

workflows:
  version: 2
  terraform:
    jobs:
      - terrascan
